<?php

namespace Modules\Property\Controllers;

use App\Http\Controllers\Controller;
use Modules\Property\Models\Property;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Room\Models\Room;
use Modules\Core\Models\Attributes;
use Illuminate\Support\Facades\Auth;
use DB;
use Modules\Property\Models\PropertyCategory;
use Modules\Booking\Models\Payment;
use Modules\Booking\Models\Booking;
use Modules\Booking\Models\Roombook;
use Modules\Roombooking\Models\RoomBooking;
use Modules\Room\Models\Availability;
use Carbon\Carbon;
use Razorpay\Api\Api;
use Session;
use Exception;

class PropertyController extends Controller
{
    protected $propertyClass;
    protected $locationClass;
    protected $propertyCategoryClass;
    protected $attributeClass;
    protected $reviewClass;
    protected $booking;
    protected $roomBooking;

    public function __construct()
    {
        $this->propertyClass         = Property::class;
        $this->locationClass         = Location::class;
        $this->propertyCategoryClass = PropertyCategory::class;
        $this->attributeClass        = Attributes::class;
        $this->reviewClass           = Review::class;
        $this->booking               = Booking::class;
        $this->roomBooking           = RoomBooking::class;
    }

    public function callAction($method, $parameters)
    {
        if (!Property::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $is_ajax = $request->query('_ajax');
        $list = call_user_func([$this->propertyClass, 'search'], $request);
        $markers = [];
        if (!empty($list)) {
            foreach ($list as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Property::frontend.layouts.search.loop-gird', ['row' => $row, 'disable_lazyload' => 1, 'wrap_class' => 'infobox-item'])->render(),
                    'marker'  => url('images/icons/png/pin.png'),
                ];
            }
        }
        $limit_location = 15;
        if (empty(setting_item("property_location_search_style")) or setting_item("property_location_search_style") == "normal") {
            $limit_location = 1000;
        }
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit($limit_location)->with(['translations'])->get()->toTree(),
            'list_category'      => $this->propertyCategoryClass::where('status', 'publish')->get()->toTree(),
            'property_min_max_price' => $this->propertyClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank"              => 1,
            "filter"             => $request->query('filter'),
            "seo_meta"           => $this->propertyClass::getSeoMetaForPageList()
        ];
        $layout = setting_item("property_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        if ($is_ajax) {
            return $this->sendSuccess([
                'html'    => view('Property::frontend.layouts.search-map.list-item', $data)->render(),
                "markers" => $data['markers']
            ]);
        }
        $data['attributes'] = $this->attributeClass::where('service', 'property')->with(['terms', 'translations'])->get();

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Property::frontend.search-map', $data);
        }
        $layout_id = $request->input('layout') ? $request->input('layout') : setting_item("property_page_search_layout", 1);
        $data['view'] = 'Property::frontend.layouts.search.list-item-rtl';
        if ($layout_id == 1) {
            $data['view'] = 'Property::frontend.layouts.search.list-item-rtl';
        } elseif ($layout_id == 2) {
            $data['view'] = 'Property::frontend.layouts.search.list-item-ltr';
        }
        return view('Property::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $layout_id = $request->input('layout') ? $request->input('layout') : setting_item("property_page_single_layout", 1);
        $limit_location = 15;
        if (empty(setting_item("property_location_search_style")) or setting_item("property_location_search_style") == "normal") {
            $limit_location = 1000;
        }
        $row = $this->propertyClass::where('slug', $slug)->with(['location', 'translations', 'hasWishList'])->first();
        if (empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }
        $translation = $row->translateOrOrigin(app()->getLocale());
        $property_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $property_related = $this->propertyClass::where('location_id', $location_id)->where("status", "publish")->take(4)->whereNotIn('id', [$row->id])->with(['location', 'translations', 'hasWishList'])->get();
        }
        $review_list = Review::where('object_id', $row->id)->where('object_model', 'property')->where("status", "approved")->orderBy("id", "desc")->with('author')->paginate(setting_item('property_review_number_per_page', 5));
        $row->view = $row->view + 1;
        $row->save();







        $data = [
            'row'               => $row,
            'translation'       => $translation,
            'property_related'  => $property_related,
            'booking_data'      => $row->getBookingData(),
            'list_location'     => $this->locationClass::where('status', 'publish')->limit($limit_location)->with(['translations'])->get()->toTree(),
            'list_category'     => $this->propertyCategoryClass::where('status', 'publish')->get()->toTree(),
            'property_min_max_price' => $this->propertyClass::getMinMaxPrice(),
            'review_list'       => $review_list,
            'seo_meta'          => $row->getSeoMetaWithTranslation(app()->getLocale(), $translation),
            'body_class'        => 'is_single',
            'rooms'             => Room::where('property_id', $row->id)->get(),
            'attributes'    => $this->attributeClass::where('service', 'property')->get(),
        ];

        $this->setActiveMenu($row);
        $blade = 'Property::frontend.detail';
        if ($layout_id == 1) {
            $blade = 'Property::frontend.detail';
        } elseif ($layout_id == 2) {
            $blade = 'Property::frontend.detail_v2';
        } elseif ($layout_id == 3) {
            $blade = 'Property::frontend.detail_v3';
        } elseif ($layout_id == 4) {
            $blade = 'Property::frontend.detail_v4';
        }

        return view($blade, $data);
    }


    public function generateRandomRoomAvailabilityData(Request $request)
    {
        $roomid     = $request->roomid;
        $propertyid = $request->propertyid;
        $userid     =  Auth::id();
         $startdate = date('Y-m-d');
        $roomvacancy = Availability::where('room_id',$roomid)->whereDate('start_date', '>=', $startdate)->get();
        $data = array();
        
        foreach($roomvacancy as $roomdata){
           
          
            $data[] = array('date' =>$roomdata->start_date,
                            'fare' => $roomdata->available_room );
        }

        return json_encode($data);

    }  
    public function propertyBooked($roomid,$propertyid,$availability)  {
       
        $old_date = explode('-', $availability); 
        $availability = $old_date[2].'-'.$old_date[1].'-'.$old_date[0];
        $data = [
            'page_title' => __('Checkout'),
            'booking'    => '',
            'service'    => '',
            'gateways'   => $this->getGateways(),
            'user'       => Auth::user()
        ];
        return view('Booking::frontend/checkout', $data);
       
    }


    public function razorPaySuccess(Request $request){

        $input = $request->all();
        $roomid = $input['product_id'];
        $startdate = date('Y-m-d');
       
        $enddate =  date('Y-m-d', strtotime($startdate. ' + 30 days'));
        $betweenday = $this->date_difference($startdate, $enddate);

        foreach($betweenday as $btwdate){
           
           $availability =  Availability::where('room_id',$roomid)->where('start_date',$btwdate['date'])->first();
           $availabiltyid = $availability->id;
           $availabiltyroom = $availability->available_room - 1;
           $query = Availability::where("id", $availabiltyid);
           $query->update(['available_room' => $availabiltyroom]);

          
        }
    
  
        $api = new Api(env('RAZORPAY_KEY'), env('RAZORPAY_SECRET'));
  
        $payment = $api->payment->fetch($input['payment_id']);

        if(count($input)  && !empty($input['payment_id'])) {
            try {
                $response = $api->payment->fetch($input['payment_id'])->capture(array('amount'=>$payment['amount']));
                
                
                $roombook = new Roombook ();

                $roombook->user_id = Auth::id();
                $roombook->room_id = $input['product_id'];
                $roombook->booking_date = date('Y-m-d') ;
                $roombook->booking_amount = $input['amount'];
                $roombook->payment_type    = $payment['method'];
                $roombook->payment_status   = $payment['status'];
                $roombook->code             = $payment['id'];
                $roombook->create_user          = Auth::id();
                $roombook->update_user          =  Auth::id();
                $roombook->save();

                if($response->status == 'captured'){
                   
                    Availability::where('room_id',$roomid)->get();
                }

               
                $payment  = new Payment ();

                $payment->booking_id = $roombook->id;
                $payment->payment_gateway = 'Rezorpay';
                $payment->amount    =$input['amount'];
                $payment->status    = $payment['status'];
                $payment->create_user=  Auth::id();
                $payment->save();


            } catch (Exception $e) {
                return  $e->getMessage();
                Session::put('error',$e->getMessage());
                return redirect()->back();
            }
        }
        $booking = array('first_name' => 'Raj',
                        'email'        => 'rajm.earney@gmail.com',
                        'id'            => $input['payment_id'],
                        'created_at'    => date('Y-m-d'),
                        'name'          => $payment['method'],
                        'status_name'   => $payment['status'],
    );
        return view('Booking::frontend/detail',$booking);
        $arr = array('msg' => 'Payment successfully credited', 'status' => true);

        return Response()->json($arr);    
    }

    function date_difference($start, $end)
    {
        $first_date = strtotime($start);
        $second_date = strtotime($end);
        $offset = $second_date-$first_date; 
        $result = array();
        for($i = 0; $i <= floor($offset/24/60/60); $i++) {
            $result[1+$i]['date'] = date('Y-m-d', strtotime($start. ' + '.$i.'  days'));
           
        }
        return $result;
       
    }

    public function RazorThankYou()
    {

        $booking = array('first_name' => 'Raj',
        'email'        => 'rajm.earney@gmail.com',
        'id'            => $input['payment_id'],
        'created_at'    => date('Y-m-d'),
        'name'          => $payment['method'],
        'status_name'   => $payment['status'],
);
return view('Booking::frontend/detail', $booking);
    }

    
    protected function getGateways()
    {

        $all = get_payment_gateways();
       
        $res = [];
        foreach ($all as $k => $item) {
           
            if (class_exists($item)) {
              
               
                $obj = new $item($k);
              
                
                if ($obj->isAvailable()) {
                    $res[$k] = $obj;
                }
            }
        }

        
        return $res;
    }
    
}
